### ISSUE TITLE
Problems with integrations stops working

### ISSUE THREAD

**Issue by cyberpater84** [wimb0/home-assistant-saj-modbus#73]
Hi,

When I call the modbus integrations in the main config YAML file the SAJ stops working properly.
Is there a solution to fixes this problem, because I am very happy with your integration so if you can please help. 

Everthing is up-to-date.

Used config in YAML:

`modbus:
  - name: "ecoforest"
    type: rtuovertcp
    host: 192.168.10.40
    port: 502
    binary_sensors:
    - name: heatpump_alarm
      slave: 17
      address: 50
    - name: Heatpump Summer
      slave: 17
      address: 127
    - name: Heatpump Winter
      slave: 17
      address: 128
    sensors:
    - name: Heatpump Buitentemperatuur
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 11
      data_type: int16
    - name: Heatpump Boiler
      unit_of_measurement: °C
      scale: 0.1
      precision: 1
      slave: 17
      address: 8
      data_type: int16`

Outcome of the falling SAJ integration
`Logger: homeassistant.setup
Source: setup.py:215
First occurred: 09:25:22 (1 occurrences)
Last logged: 09:25:22

Setup failed for custom integration saj_modbus: Unable to import component: Exception importing custom_components.saj_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/saj_modbus/__init__.py", line 16, in <module>
    from .hub import SAJModbusHub
  File "/config/custom_components/saj_modbus/hub.py", line 13, in <module>
    from pymodbus.payload import BinaryPayloadDecoder
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 28, in <module>
    class BinaryPayloadBuilder:
  File "/usr/local/lib/python3.11/site-packages/pymodbus/payload.py", line 42, in BinaryPayloadBuilder
    self, payload=None, byteorder=Endian.Little, wordorder=Endian.Big, repack=False
                                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: Little

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.saj_modbus`

**Comment by cyberpater84** [comment]
Goedemiddag,

Het zou wel erg fijn zijn als de integratie een update krijgt naar de laatste PYmodbus, want het het draait nog steeds niet als ik mijn modbus aanspreek in de YAML config. 

De complete SAJ modus stopt dan met functioneren.

**Comment by cyberpater84** [comment]
It is working thanks a lot, will this be a problem evetime the main pyp modbus will get a update. And is there anything I can do to avoid this problem. Because I am very happy whit applications of yours
